server/libs/app/__init__.py
from importlib import import_module

from flask import Flask, render_template, request
from werkzeug.exceptions import HTTPException

from libs.webserver.messages import BadRequest, MethodNotAllowed, NotFound, ServerError


def bad_request(_: HTTPException) -> tuple:
    return BadRequest.as_response()


def not_found(e: HTTPException) -> tuple:
    if request.path.startswith("/api/"):
        return NotFound.as_response()
    return render_template("home/error.html", code=e.code, message="Page not found"), e.code


def method_not_allowed(e: HTTPException) -> tuple:
    if request.path.startswith("/api/"):
        return MethodNotAllowed.as_response()
    return render_template("home/error.html", code=e.code, message="Method not allowed"), e.code


def server_error(e: HTTPException) -> tuple:
    if request.path.startswith("/api/"):
        return ServerError.as_response()
    return render_template("home/error.html", code=e.code, message="Server error"), e.code


def register_blueprints(app: Flask) -> None:
    for module_name in ["home"]:
        module = import_module(f"libs.app.{module_name}.routes")
        app.register_blueprint(module.blueprint)


def register_errors(app: Flask) -> None:
    app.register_error_handler(400, bad_request)
    app.register_error_handler(404, not_found)
    app.register_error_handler(405, method_not_allowed)
    app.register_error_handler(500, server_error)


def create_app() -> Flask:
    app = Flask(__name__, static_folder="static")
    register_blueprints(app)
    register_errors(app)
    return app

server/libs/app/home/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    "home_blueprint",
    __name__,
    url_prefix=""
)

server/libs/app/home/routes.py
from flask import abort, render_template, request
from flask_login import login_required
from jinja2 import TemplateNotFound

from libs.app.home import blueprint
from libs.webserver.executer import Executer


@blueprint.get("/dashboard")
@blueprint.get("/")
@login_required
def index():
    devices = Executer.instance.device_executer.get_devices()
    assigned_groups = Executer.instance.device_executer.get_assigned_groups()
    return render_template("home/dashboard.html", segment="dashboard", devices=devices, groups=assigned_groups)


@blueprint.get("/system_status")
@login_required
def route_system_status():
    segment = get_segment()
    return render_template("home/system_status.html", segment=segment)


@blueprint.get("/effects/<template>")
@login_required
def route_effect_settings(template: str):
    devices = Executer.instance.device_executer.get_devices()
    assigned_groups = Executer.instance.device_executer.get_assigned_groups()

    try:
        segment = get_segment()
        return render_template(f"home/effects/{template}.html", segment=segment, devices=devices, groups=assigned_groups)
    except TemplateNotFound:
        abort(404)
    except Exception:  # noqa: BLE001
        abort(500)


@blueprint.get("/settings/<template>")
@login_required
def route_settings(template: str):
    devices = Executer.instance.device_executer.get_devices()
    groups = Executer.instance.device_executer.get_groups()

    try:
        segment = get_segment()
        return render_template(f"home/settings/{template}.html", segment=segment, devices=devices, groups=groups)
    except TemplateNotFound:
        abort(404)
    except Exception:  # noqa: BLE001
        abort(500)


def get_segment() -> str:
    """Extract current page name from request."""
    try:
        segment = request.path.split("/")[-1]
        if not segment:
            segment = "dashboard"
        return segment
    except Exception:  # noqa: BLE001
        return None

server/libs/app/templates/home/effects/effect_border.html
{% extends "layouts/base.html" %}

{% block title %} Edit Effect Border {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">

            {% include 'includes/toasts.html' %}

            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Border</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.index') }}"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Edit Effects</a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Border</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->

                    {% include 'includes/devices.html' %}

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Border Effect Settings</h5>
                                </div>
                                <div class="card-block">
                                    <p>Edit the Border effect. If "Manually resize bars" is checked, only 4 bars are available (For each wall side).</p>
                                    <input type="hidden" id="settingsIdentifier" value="effect">
                                    <input type="hidden" id="effectIdentifier" value="effect_border">
                                    <form id="settingsForm" action method="post" novalidate autocomplete="off">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Single Color</label>
                                                    <select name="color:string" id="color" class="form-control colors setting_input"></select>
                                                </div>
                                                <div class="custom-control custom-checkbox my-2">
                                                    <input name="manually_resize_bars:boolean" type="checkbox" class="custom-control-input setting_input" id="manually_resize_bars">
                                                    <label class="custom-control-label" for="manually_resize_bars">Manually resize bars</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Gradient</label>
                                                    <select name="gradient:string" id="gradient" class="form-control gradients setting_input"></select>
                                                </div>
                                                <div class="custom-control custom-checkbox my-2">
                                                    <input name="use_gradient:boolean" type="checkbox" class="custom-control-input setting_input" id="use_gradient">
                                                    <label class="custom-control-label" for="use_gradient">Use Gradient</label>
                                                </div>
                                                <div class="custom-control custom-checkbox my-2">
                                                    <input name="mirror:boolean" type="checkbox" class="custom-control-input setting_input" id="mirror">
                                                    <label class="custom-control-label" for="mirror">Mirror</label>
                                                </div>
                                                <div class="custom-control custom-checkbox my-2">
                                                    <input name="reverse_roll:boolean" type="checkbox" class="custom-control-input setting_input" id="reverse_roll">
                                                    <label class="custom-control-label" for="reverse_roll">Reverse Roll</label>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Bar Count <span for="bar_count" class="mb-0 badge badge-secondary"></span></label>
                                                    <input name="bar_count:number" id="bar_count" type="range" class="custom-range setting_input" min="0" max="24" step="1" required>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Roll Speed <span for="roll_speed" class="mb-0 badge badge-secondary"></span></label>
                                                    <input name="roll_speed:number" id="roll_speed" type="range" class="custom-range setting_input" min="0" max="10" step="0.1" required>
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Segment 01 Start</label>
                                                    <input name="segment_01_start:number" id="segment_01_start" class="form-control setting_input" type="number" name="number" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Segment 01 End</label>
                                                    <input name="segment_01_end:number" id="segment_01_end" class="form-control setting_input" type="number" name="number" required>
                                                </div>

                                                <hr class="my-4">

                                                <div class="form-group">
                                                    <label>Segment 02 Start</label>
                                                    <input name="segment_02_start:number" id="segment_02_start" class="form-control setting_input" type="number" name="number" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Segment 02 End</label>
                                                    <input name="segment_02_end:number" id="segment_02_end" class="form-control setting_input" type="number" name="number" required>
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Segment 03 Start</label>
                                                    <input name="segment_03_start:number" id="segment_03_start" class="form-control setting_input" type="number" name="number" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Segment 03 End</label>
                                                    <input name="segment_03_end:number" id="segment_03_end" class="form-control setting_input" type="number" name="number" required>
                                                </div>

                                                <hr class="my-4">

                                                <div class="form-group">
                                                    <label>Segment 04 Start</label>
                                                    <input name="segment_04_start:number" id="segment_04_start" class="form-control setting_input" type="number" name="number" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Segment 04 End</label>
                                                    <input name="segment_04_end:number" id="segment_04_end" class="form-control setting_input" type="number" name="number" required>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="mt-4 d-flex flex-md-row flex-column justify-content-md-end">
                                            <button type="button" id="save_btn" class="btn btn-success m-0">Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{{ url_for('static', filename='assets/js/settings.effect.js') }}" type="module"></script>
{% endblock javascripts %}

server/libs/app/templates/home/effects/effect_direction_changer.html
{% extends "layouts/base.html" %}

{% block title %} Edit Effect Direction Changer {% endblock %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="pcoded-content">
        <div class="pcoded-inner-content">

            {% include 'includes/toasts.html' %}

            <!-- [ breadcrumb ] start -->
            <div class="page-header">
                <div class="page-block">
                    <div class="row align-items-center">
                        <div class="col-md-12">
                            <div class="page-header-title">
                                <h5 class="m-b-10">Direction Changer</h5>
                            </div>
                            <ul class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{ url_for('home_blueprint.index') }}"><i class="feather icon-home"></i></a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Edit Effects</a></li>
                                <li class="breadcrumb-item"><a href="javascript:">Direction Changer</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- [ breadcrumb ] end -->
            <div class="main-body">
                <div class="page-wrapper">
                    <!-- [ Main Content ] start -->

                    {% include 'includes/devices.html' %}

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="card">
                                <div class="card-header">
                                    <h5>Direction Changer Effect Settings</h5>
                                </div>
                                <div class="card-block">
                                    <p>Edit the Direction Changer effect.</p>
                                    <input type="hidden" id="settingsIdentifier" value="effect">
                                    <input type="hidden" id="effectIdentifier" value="effect_direction_changer">
                                    <form id="settingsForm" action method="post" novalidate autocomplete="off">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Single Color</label>
                                                    <select name="color:string" id="color" class="form-control colors setting_input"></select>
                                                </div>
                                                <div class="form-group">
                                                    <label>Speed <span for="bar_speed" class="mb-0 badge badge-secondary"></span></label>
                                                    <input name="bar_speed:number" id="bar_speed" type="range" class="custom-range setting_input" min="0" max="20" step="1" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Bar Length <span for="bar_length" class="mb-0 badge badge-secondary"></span></label>
                                                    <input name="bar_length:number" id="bar_length" type="range" class="custom-range setting_input" min="0" max="20" step="1" required>
                                                </div>
                                                <div class="form-group">
                                                    <label>Amount of Bars in the Same Direction <span for="bars_in_same_direction" class="mb-0 badge badge-secondary"></span></label>
                                                    <input name="bars_in_same_direction:number" id="bars_in_same_direction" type="range" class="custom-range setting_input" min="0" max="20" step="1" required>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <label>Gradient</label>
                                                    <select name="gradient:string" id="gradient" class="form-control gradients setting_input"></select>
                                                </div>
                                                <div class="custom-control custom-checkbox my-2">
                                                    <input name="colorful_mode:boolean" type="checkbox" class="custom-control-input setting_input" id="colorful_mode">
                                                    <label class="custom-control-label" for="colorful_mode">Use Gradient</label>
                                                </div>
                                                <div class="custom-control custom-checkbox my-2">
                                                    <input name="random_color:boolean" type="checkbox" class="custom-control-input setting_input" id="random_color">
                                                    <label class="custom-control-label" for="random_color">Randomly Select Gradient Color</label>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="mt-4 d-flex flex-md-row flex-column justify-content-md-end">
                                            <button type="button" id="save_btn" class="btn btn-success m-0">Save</button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- [ Main Content ] end -->
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script src="{{ url_for('static', filename='assets/js/settings.effect.js') }}" type="module"></script>
{% endblock javascripts %}

server/libs/app/templates/home/error.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} {{ code }} Page {% endblock %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <i class="feather x-circle"></i>
                    </div>
                    <h3 class="mb-4">Error {{ code }}</h3>

                    <br />

                    <span class="mb-0 text-muted">
                        {{ message|default('An error occured') }} - <a href="{{ url_for('home_blueprint.index') }}">Home</a>
                    </span>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

server/libs/app/templates/home/login.html
{% extends "layouts/base-fullscreen.html" %}

{% block title %} Login {% endblock %}

{% block content %}

    <div class="auth-wrapper">
        <div class="auth-content">
            <div class="auth-bg">
                <span class="r"></span>
                <span class="r s"></span>
                <span class="r s"></span>
                <span class="r"></span>
            </div>
            <div class="card">
                <div class="card-body text-center">
                    <div class="mb-4">
                        <img src="{{ url_for('static', filename='assets/images/mlsc_icon.svg') }}" alt="MLSC" draggable="false" width="50px">
                    </div>

                    <span class="h4 mb-0 text-muted">
                        Dashboard
                    </span>

                    <form class="mt-4" role="form" method='POST' novalidate>
                        {% with messages = get_flashed_messages() %}
                            <div class="input-group">
                                <input type="password" class="form-control {{'is-invalid' if messages}}" placeholder="PIN" name="pin" minlength="4" maxlength="8" autofocus>
                            </div>
                            {% if messages %}
                                {% for message in messages %}
                                    <div class="mt-1 text-danger text-left">
                                        {{message}}
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <div class="{{'mt-2' if messages else 'mt-4'}} d-flex flex-md-row flex-column justify-content-md-center">
                                <button type="submit" name="submit" class="btn btn-primary m-0">Unlock</button>
                            </div>
                        {% endwith %}
                    </form>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
{% endblock javascripts %}

server/libs/app/templates/includes/macros.html
{% macro nav_link(endpoint, name) %}
    {% if endpoint.endswith(segment) %}
        <li class="active"><a href="{{ endpoint }}">{{ name }}</a></li>
    {% else %}
        <li><a href="{{ endpoint }}">{{ name }}</a></li>
    {% endif %}
{% endmacro %}

server/libs/app/templates/includes/navigation.html
    <header class="navbar pcoded-header navbar-expand-lg d-lg-none">
        <div class="m-header">
            <a class="mobile-menu" id="mobile-collapse" href="#!"><span></span></a>
            <a href="{{ url_for('home_blueprint.index') }}" class="b-brand">
                <div class="nav-item pcoded-menu-caption">
                    <img class="logo" src="{{ url_for('static', filename='assets/images/mlsc_logo.svg') }}" alt="MLSC" draggable="false"/>
                </div>
            </a>
        </div>
    </header>

server/libs/app/templates/includes/sidebar.html
{% from "includes/macros.html" import nav_link with context %}

<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <div class="b-brand">
                <img src="{{ url_for('static', filename='assets/images/mlsc_icon.svg') }}" alt="MLSC" draggable="false" width="40px">
                <span class="b-title">MLSC</span>
            </div>
            <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>
        </div>

        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li class="nav-item pcoded-menu-caption">
                    <label>Navigation</label>
                </li>
                <li class="nav-item {{'active' if segment == 'dashboard'}}">
                    <a href="{{ url_for('home_blueprint.index') }}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
                </li>
                <li class="nav-item {{'active' if segment == 'system_status'}}">
                    <a href="{{ url_for('home_blueprint.route_system_status') }}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-activity"></i></span><span class="pcoded-mtext">System Status</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>General</label>
                </li>
                <li class="nav-item pcoded-hasmenu {{'pcoded-trigger' if 'effect_' in segment}}">
                    <a href="javascript:" class="nav-link"><span class="pcoded-micon"><i class="feather icon-edit"></i></span><span class="pcoded-mtext">Edit Effects</span></a>
                    <ul id="effect_list" class="pcoded-submenu">
                        <li class="py-0 nav-item pcoded-menu-caption">
                            <label>Special Effects</label>
                        </li>
                        {{ nav_link('/effects/effect_random_cycle', 'Random Cycle') }}

                        <li class="pb-0 nav-item pcoded-menu-caption">
                            <label>Non-Music Effects</label>
                        </li>
                        {{ nav_link('/effects/effect_single', 'Single') }}
                        {{ nav_link('/effects/effect_gradient', 'Gradient') }}
                        {{ nav_link('/effects/effect_fade', 'Fade') }}
                        {{ nav_link('/effects/effect_sync_fade', 'Sync Fade') }}
                        {{ nav_link('/effects/effect_slide', 'Slide') }}
                        {{ nav_link('/effects/effect_bubble', 'Bubble') }}
                        {{ nav_link('/effects/effect_twinkle', 'Twinkle') }}
                        {{ nav_link('/effects/effect_pendulum', 'Pendulum') }}
                        {{ nav_link('/effects/effect_rods', 'Rods') }}
                        {{ nav_link('/effects/effect_segment_color', 'Segment Color') }}
                        {{ nav_link('/effects/effect_fireplace', 'Fireplace') }}
                        {{ nav_link('/effects/effect_strobe', 'Strobe') }}

                        <li class="pb-0 nav-item pcoded-menu-caption">
                            <label>Music Effects</label>
                        </li>
                        {{ nav_link('/effects/effect_scroll', 'Scroll') }}
                        {{ nav_link('/effects/effect_advanced_scroll', 'Advanced Scroll') }}
                        {{ nav_link('/effects/effect_energy', 'Energy') }}
                        {{ nav_link('/effects/effect_wavelength', 'Wavelength') }}
                        {{ nav_link('/effects/effect_bars', 'Bars') }}
                        {{ nav_link('/effects/effect_power', 'Power') }}
                        {{ nav_link('/effects/effect_beat', 'Beat') }}
                        {{ nav_link('/effects/effect_beat_twinkle', 'Beat Twinkle') }}
                        {{ nav_link('/effects/effect_beat_slide', 'Beat Slide') }}
                        {{ nav_link('/effects/effect_wave', 'Wave') }}
                        {{ nav_link('/effects/effect_wiggle', 'Wiggle') }}
                        {{ nav_link('/effects/effect_vu_meter', 'VU Meter') }}
                        {{ nav_link('/effects/effect_spectrum_analyzer', 'Spectrum Analyzer') }}
                        {{ nav_link('/effects/effect_direction_changer', 'Direction Changer') }}
                        {{ nav_link('/effects/effect_border', 'Border') }}
                    </ul>
                </li>
                <li class="nav-item pcoded-hasmenu {{'pcoded-trigger' if '_settings' in segment}}">
                    <a href="javascript:" class="nav-link"><span class="pcoded-micon"><i class="feather icon-settings"></i></span><span class="pcoded-mtext">Settings</span></a>
                    <ul id="settings_list" class="pcoded-submenu">
                        {{ nav_link('/settings/general_settings', 'General Settings') }}
                        {{ nav_link('/settings/device_settings', 'Device Settings') }}
                        <!-- {{ nav_link('/settings/microphone_adjustment', 'Microphone Adjustment') }} -->
                    </ul>
                </li>
                <li class="nav-item pcoded-menu-caption {{'d-none' if not current_user.is_authenticated}}">
                    <label>Security</label>
                </li>
                <li class="nav-item {{'d-none' if not current_user.is_authenticated}}">
                    <a href="{{ url_for('authentication_api.logout') }}" class="nav-link"><span class="pcoded-micon"><i class="feather icon-lock"></i></span><span class="pcoded-mtext">Lock Dashboard</span></a>
                </li>
                <li class="nav-item pcoded-menu-caption">
                    <label>Information</label>
                </li>
                <li class="nav-item">
                    <a href="https://github.com/TobKra96/music_led_strip_control" target="_blank" rel="noopener noreferrer" class="nav-link"><span class="pcoded-micon"><i class="feather icon-github"></i></span><span class="pcoded-mtext">GitHub Homepage</span></a>
                </li>
                <li class="nav-item">
                    <a href="https://discord.gg/Xa28JAvAZA" target="_blank" rel="noopener noreferrer" class="nav-link"><span class="pcoded-micon"><i class="feather icon-message-square"></i></span><span class="pcoded-mtext">Discord Channel</span></a>
                </li>
                <li class="nav-item mb-4">
                    <a href="{{ url_for('flask_openapi.apidocs') }}" target="_blank" rel="noopener noreferrer" class="nav-link"><span class="pcoded-micon"><i class="feather icon-file"></i></span><span class="pcoded-mtext">API Documentation</span></a>
                </li>
            </ul>
        </div>
    </div>
</nav>